#############################################################################
# Generated by PAGE version 4.24
#  in conjunction with Tcl version 8.6
#  Jul 23, 2019 03:17:50 PM CEST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}



if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}


proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d8d8d8} 
    wm focusmodel $top passive
    wm geometry $top 760x511+541+155
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    canvas $top.can44 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 341 \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 371 
    vTcl:DefineAlias "$top.can44" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.can44
    button $site_3_0.but49 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Load Video} 
    vTcl:DefineAlias "$site_3_0.but49" "Button4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but49 \
        -in $site_3_0 -x 240 -y 10 -anchor nw -bordermode ignore 
    canvas $top.can45 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 341 \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 361 
    vTcl:DefineAlias "$top.can45" "Canvas2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.can45
    button $site_3_0.but50 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Load Video} 
    vTcl:DefineAlias "$site_3_0.but50" "Button5" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but50 \
        -in $site_3_0 -x 230 -y 10 -anchor nw -bordermode ignore 
    button $top.but46 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Play 
    vTcl:DefineAlias "$top.but46" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Play 
    vTcl:DefineAlias "$top.but47" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but48 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Play Both} 
    vTcl:DefineAlias "$top.but48" "Button3" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe52 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe52" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can44 \
        -in $top -x 10 -y 40 -width 371 -relwidth 0 -height 341 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.can45 \
        -in $top -x 390 -y 40 -width 361 -relwidth 0 -height 341 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 130 -y 390 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 540 -y 390 -width 61 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 10 -y 470 -width 741 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSe52 \
        -in $top -x 386 -y 20 -width 2 -height 430 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

